# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTm2FfDCkS8wGnrHMZWOnEJxW7zRhzZG

Import Libraries
"""

import pandas as pd
import numpy as np

"""Loading  Dataset"""

data = pd.read_csv("/content/IRIS_Dataset.csv")

data.shape

data.columns

data.head()

"""Checking Dataset Information"""

print(data.info())

print(data.isnull().sum)

"""Converting Species into Numbers"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['species'] = le.fit_transform(data['species'])

"""Select Features and Target"""

X = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = data['species']

"""Spliting Dataset"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

"""Creating Classification Model"""

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

"""Training Model"""

model.fit(X_train, y_train)

"""Predict Species"""

y_pred = model.predict(X_test)

"""Check Accuracy"""

from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

"""Show Species Count"""

species_count = data['species'].value_counts()
print("\nSpecies Count:")
print(species_count)
print("\nExplanation:")
print("0 = Iris-setosa")
print("1 = Iris-versicolor")
print("2 = Iris-virginica")

"""Creating Graph"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(3,3))
sns.countplot(x='species', data=data)
plt.title("Iris Flower Species Count")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()